deb: use appropriate separator for lintian
It fixes the following error:

  Please use spaces as separators in field Disable-Tags instead of commas in profile /root/.lintian/profiles/fluent-package/ubuntu.profile
  Error: The operation was canceled.

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>