deb: fix missing architectures for only _all.deb
It fixes the publish error:

   aptly -config=/work/fluentd/fluent-package-builder/.aptly.conf publish snapshot -component=contrib -gpg-key=BEE682289B2217F45AF4CC3F901F9177AB97ACBE fluent-package5-bullseye-5.0.0-1 bullseye
  Loading packages...
  ERROR: unable to publish: unable to figure out list of architectures, please supply explicit list

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>