Backport(v6): rpm: fix update error if working directory is missing (#955) (#977)
Backport https://github.com/fluent/fluent-package-builder/pull/955

If `/tmp/fluent/` was removed, it causes error when update to Fluent
Package 6.0.x as following:

```
# dnf install ./fluent-package-5.0.9-1.el8.x86_64.rpm

# rm -rf /tmp/fluent/

# dnf install -y ./fluent-package-6.0.1-1.el8.x86_64.rpm
Last metadata expiration check: 0:55:01 ago on Tue Feb 10 05:05:41 2026.
Dependencies resolved.
====================================================================================================================================================================
 Package                                   Architecture                      Version                                  Repository                               Size
====================================================================================================================================================================
Upgrading:
 fluent-package                            x86_64                            6.0.1-1.el8                              @commandline                             23 M

Transaction Summary
====================================================================================================================================================================
Upgrade  1 Package

Total size: 23 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                            1/1
  Running scriptlet: fluent-package-6.0.1-1.el8.x86_64                                                                                                          1/1
  Running scriptlet: fluent-package-6.0.1-1.el8.x86_64                                                                                                          1/2
/var/tmp/rpm-tmp.Fp7H9o: line 39: /tmp/fluent/.local_base_plugins: No such file or directory
error: %prein(fluent-package-6.0.1-1.el8.x86_64) scriptlet failed, exit status 1

Error in PREIN scriptlet in rpm package fluent-package
  Verifying        : fluent-package-6.0.1-1.el8.x86_64                                                                                                          1/2
  Verifying        : fluent-package-5.0.9-1.el8.x86_64                                                                                                          2/2

Failed:
  fluent-package-5.0.9-1.el8.x86_64                                                fluent-package-6.0.1-1.el8.x86_64

Error: Transaction failed
```

---------

Signed-off-by: Shizuo Fujita <fujita@clear-code.com>
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
Co-authored-by: Kentaro Hayashi <hayashi@clear-code.com>