Fix system user/group name in logrotate config (#592)
Fix system user/group name in logrotate config

I had installed  `fluent-package` - `5.0.1-1` on ubuntu 22.04
```
ii  fluent-package 5.0.1-1      amd64        All in one package of Fluentd
```

With fluent-package v5 user/group name is changed to `_fluentd`
-
https://github.com/fluent/fluent-package-builder/blob/v5.0.1/fluent-package/templates/package-scripts/fluent-package/deb/postinst#L13
-
https://github.com/fluent/fluent-package-builder/blob/v5.0.1/fluent-package/templates/package-scripts/fluent-package/deb/postinst#L19

However user/group name in logrotate config is `fluentd`, which causes
following failure
```
$ logrotate -f /etc/logrotate.d/fluentd
error: /etc/logrotate.d/fluentd:7 unknown user 'fluentd'
error: found error in /var/log/fluent/fluentd.log , skipping
```
I guess this change was introduced in -
https://github.com/fluent/fluent-package-builder/pull/449

Signed-off-by: Rahul Patil <rahulbpatil10@yahoo.co.jp>